### ISSUE TITLE
Doesn't work :)

### ISSUE THREAD

**Issue by cinilak** [sauter-hq/git-guidelines#1]
So I tried it on Windows 7
Restarted git bash, still was asking for ssh pass after first entry
Restarted PC, same issue

**Comment by cinilak** [comment]
ok, so instead of .bashrc, stuff should go into .bash_profile

**Comment by daminetreg** [comment]
Dear @cinilak,

Thank you for reporting this, I fixed the page accordingly.

Warm regards

**Comment by cinilak** [comment]
Thank you for creating this guide :)

All the best
